In [3]:
import numpy as np
arr = np.arange(5 * 8).reshape(5, 8)
print(arr)
print()
reversed_rows = arr[::-1]
print(reversed_rows)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]

[[32 33 34 35 36 37 38 39]
 [24 25 26 27 28 29 30 31]
 [16 17 18 19 20 21 22 23]
 [ 8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7]]


In [8]:
import numpy as np

arr = np.arange(3*1*120*160*3).reshape(3,1,120,160,3)
# print(arr)
print(arr[0,0,1,1,:])
print()
reversed_rows = arr[::-1]
print(reversed_rows[2,0,1,1,:])

[483 484 485]

[483 484 485]
